alias g=git
alias ub="ssh -p 2222 ubuntu@localhost"
alias cl="ssh ubuntu@ec2-50-18-33-85.us-west-1.compute.amazonaws.com"
alias py=python
alias rb=ruby
alias ka="killall"
alias ss=ssh
alias s=sudo
alias l="ls -al"
alias v="vim -p"
alias c="cd"
